import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

import ReactQueryProvider from './utils/providers/react-query'

const inter = Poppins({
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Coffee Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={inter.className}>{children}</body>
      </ReactQueryProvider>
    </html>
  )
}
