import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'

import ReactQueryProvider from '../hooks/providers/react-query'
import { ToastContainer } from 'react-toastify'

const inter = Poppins({
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Coffee Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <html lang="en">
        <ReactQueryProvider>
          <body className={inter.className}>
            {children}
            <ToastContainer />
          </body>
        </ReactQueryProvider>
      </html>
    </>
  )
}
